version: '2'

services:

  server:
    build:
      context: ../../../server
    image: webalyse/1click
    environment:
      - POSTGRES_USER=${postgres_user}
      - POSTGRES_PASSWORD=${postgres_password}
    ports:
      - ${server_host_port}:80
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: oneclick
      POSTGRES_PASSWORD: oneclick
    ports:
      - ${postgres_host_port}:5432
    volumes:
      - 1click-postgres:/var/lib/postgresql/data

volumes:
  1click-postgres: