version: '3'

services:

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    image: oneclick:latest
    ports:
      - "8080:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: oneclick
      POSTGRES_PASSWORD: oneclick
    ports:
      - "5432:5432"
    volumes:
      - oneclick-postgres:/var/lib/postgresql/data

volumes:
  oneclick-postgres: